apiVersion: v1
kind: Template
metadata:
  name: syndesis-ci
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      app: syndesis-ci
    name: jenkins-data
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
