apiVersion: v1
kind: ImageStream
metadata:
  name: maven-with-repo
  labels:
    app: syndesis
    component: syndesis-ci
spec:
  tags:
  - from:
      kind: DockerImage
      name: 172.30.39.149:5000/syndesis/maven-with-repo:latest
    importPolicy:
      scheduled: true
    name: "latest"
