apiVersion: v1
kind: Template
metadata:
  name: nexus
parameters:
- name: KUBERNETES_NAMESPACE
  description: The target namespace
  value: syndesis-ci
- name: ROUTE_HOSTNAME
  description: The external hostname to access the iPaaS
  value: jenkins-syndesis-ci.b6ff.rh-idev.openshiftapps.com
  required: true
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: nexus
    name: nexus
  spec:
    tags:
    - annotations:
        openshift.io/imported-from: fabric8/nexus
      from:
        kind: DockerImage
        name: fabric8/nexus:latest
      importPolicy: {}
      name: latest
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: nexus
    labels:
      app: nexus
  spec:
    replicas: 1
    selector:
      app: nexus
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
        labels:
          app: nexus
      spec:
        containers:
        - image: fabric8/nexus
          imagePullPolicy: Always
          name: nexus
          ports:
          - containerPort: 8081
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /sonatype-work
            name: nexus-volume
          - mountPath: /usr/local/share/nexus.xml
            name: nexus-config-volume
            subPath: nexus.xml.file
          readinessProbe:
            httpGet:
              port: 8081
            initialDelaySeconds: 300
            timeoutSeconds: 1
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: nexus-volume
          persistentVolumeClaim:
            claimName: nexus-volume
        - name: nexus-config-volume
          configMap:
            name: nexus-config-map
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - nexus
        from:
          kind: ImageStreamTag
          name: nexus:latest
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: nexus
    name: nexus
  spec:
    ports:
    - name: 8081-tcp
      port: 8081
      protocol: TCP
      targetPort: 8081
    selector:
      app: nexus
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: nexus
    name: nexus
  spec:
    host: ${ROUTE_HOSTNAME}
    path: /
    port:
      targetPort: 8081
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: nexus
      weight: 100
